name: 🕵️‍♂️ EditorConfig checker

on:
  pull_request:
    branches: [main]

jobs:
  editorconfig:
    name: 🕵️‍♂️ EditorConfig checker
    runs-on: ubuntu-22.04
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5

      - name: ⤵️ Download EditorConfig checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: 🚀 Run EditorConfig checker
        run: editorconfig-checker
